### ISSUE TITLE
Unable to terminate shell

### ISSUE THREAD

**Issue by kepler155c** [MCJack123/cash#3]
All is looking good but I have one last issue. If I run cash.lua, I am not able to terminate it directly - I must use the exit command. I believe the cash process should handle the terminate event and exit accordingly.

**Comment by MCJack123** [comment]
This behavior is intended to function the same as (ba)sh: pressing ^C in a shell session just cancels the current command and never quits. I can add an option or variable to make it so ^T will terminate the shell, but I think the current behavior should be kept.

**Comment by kepler155c** [comment]
This is very non-standard for cc (and causes quite a few issues in Opus).

**Comment by MCJack123** [comment]
I added a variable called `TERMINATE_QUIT` that if set to `yes` or `1`, sending the terminate event will quit the shell. You can add `TERMINATE_QUIT=yes` to the default .cashrc file in Opus to fix whatever issues you were having.
